# NOTE: to be applied manually
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: external-postgres
  namespace: external
  labels:
    kubernetes.io/service-name: external-postgres
addressType: IPv4
ports:
  - name: postgres
    protocol: TCP
    port: 5432
endpoints:
  - addresses:
      - "192.168.0.90"
