# NOTE: to be applied manually
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: external-proxmox
  namespace: external
  labels:
    kubernetes.io/service-name: external-proxmox
addressType: IPv4
ports:
  - name: https # should match with the name of the service port defined above
    appProtocol: https
    protocol: TCP
    port: 8006
endpoints:
  - addresses:
      - "192.168.0.50"
      - "192.168.0.60"
    # https://github.com/traefik/traefik/issues/12389
    # need to include this otherwise traefik fails with no server available
    conditions:
      ready: true
