apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  destination:
    namespace: external-secrets
    server: "https://kubernetes.default.svc"
  sources:
    - chart: external-secrets
      repoURL: "https://charts.external-secrets.io"
      targetRevision: 1.2.0
      #helm:
      #  valueFiles:
      #    - $values/2-infra/dev/external-secrets/values/values.yaml
    # values files reference
    #- repoURL: "https://github.com/eeternalsadness/homelab.git"
    #  targetRevision: main
    #  ref: values
    # resources
    #- repoURL: "https://github.com/eeternalsadness/homelab.git"
    #  targetRevision: main
    #  path: 2-infra/dev/external-secrets/resources
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
