apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: external
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://github.com/eeternalsadness/homelab.git"
    targetRevision: main
    path: 2-infra/dev/external/resources
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
