apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: metallb-system
    server: "https://kubernetes.default.svc"
  sources:
    # install helm chart
    - chart: metallb
      repoURL: "https://metallb.github.io/metallb"
      targetRevision: 0.15.3
    # IP address pool & L2 advertisement
    - repoURL: "https://github.com/eeternalsadness/homelab.git"
      targetRevision: main
      path: 2-infra/dev/metallb/resources
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      # required if PSA is enabled
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
