{{- range .Values.envs }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  destination:
    namespace: cert-manager
    server: "https://kubernetes.default.svc"
  sources:
    - chart: cert-manager
      repoURL: "https://charts.jetstack.io"
      targetRevision: 1.17.2
      helm:
        valueFiles:
          - $values/envs/{{ . }}/cert-manager/values/values.yaml
    # values files reference
    - repoURL: "https://github.com/eeternalsadness/homelab.git"
      targetRevision: minikube
      ref: values
    # resources
    - repoURL: "https://github.com/eeternalsadness/homelab.git"
      targetRevision: minikube
      path: envs/{{ . }}/cert-manager/resources
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
