apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qdrant
  namespace: argocd
spec:
  project: default
  destination:
    namespace: qdrant
    server: "https://kubernetes.default.svc"
  source:
    chart: qdrant
    repoURL: "https://qdrant.github.io/qdrant-helm"
    targetRevision: 1.14.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

