apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  destination:
    namespace: vault
    server: "https://kubernetes.default.svc"
  source:
    chart: vault
    repoURL: "https://helm.releases.hashicorp.com"
    targetRevision: 0.29.1
    helm:
      parameters:
        - name: "logLevel"
          value: "debug"
  # ignore mutating webhook diffs
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
