apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-internal
  namespace: argocd
  finalizers:
    - resource-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  source:
    path: "1-argocd-apps/3-infra/internal/dev"
    repoURL: "https://github.com/eeternalsadness/homelab.git"
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
