grafana:
  defaultDashboardsTimezone: Asia/Bangkok

  #  ingress:
  #    enabled: true
  #    ingressClassName: traefik
  #    path: /grafana

  resources: {}

  # NOTE: for auto discovery of resources (dashboards, alerts, data sources, etc.)
  #sidecar:
  #  resources: {}
  #  dashboards:
  #    enabled: true
  #    label: grafana_dashboard # label to look for
  #    labelValue: "1" # label value to look for
  #    searchNamespace: ALL # search in all namespaces
  #  alerts:
  #    enabled: true
  #    label: grafana_alert
  #    labelValue: "1"
  #    searchNamespace: ALL # search in all namespaces
  #  datasources:
  #    enabled: true
  #    label: grafana_datasource
  #    labelValue: "1"
  #    searchNamespace: ALL # search in all namespaces
  #  plugins:
  #    enabled: true
  #    label: grafana_plugin
  #    labelValue: "1"
  #    searchNamespace: ALL # search in all namespaces
