apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd # same namespace as workload
spec:
  secretName: argocd-tls
  issuerRef:
    name: cluster-issuer # name of ClusterIssuer object
    kind: ClusterIssuer
  dnsNames:
    - argocd.minikube.local # match with ingress hostname
