apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

generatorOptions:
  # common label for grafana sidecar to pick up resource
  labels:
    grafana_dashboard: "1"

configMapGenerator:
  - name: grafana-contact-points
    files:
      - contact-points/contact-points.json
