apiVersion: v1
kind: Service
metadata:
  name: external-pihole
spec:
  type: ExternalName
  externalName: rpi-1.home.lan
  internalTrafficPolicy: Cluster
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pihole-cert
spec:
  secretName: pihole-tls
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - pihole.homelab.eeternalsadness.dev
---
# Replace the path with /admin
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: external-pihole-replacepathregex
spec:
  replacePathRegex:
    regex: "^/$"
    replacement: "/admin/"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: external-pihole
  annotations:
    gethomepage.dev/href: "https://pihole.homelab.eeternalsadness.dev"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Pi-hole
    gethomepage.dev/group: Management
    gethomepage.dev/icon: pi-hole.png # icons from https://github.com/homarr-labs/dashboard-icons/tree/main/png
    gethomepage.dev/name: Pi-hole
    # external dns
    external-dns.alpha.kubernetes.io/target: "traefik-lb.homelab.eeternalsadness.dev"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`pihole.homelab.eeternalsadness.dev`)
      middlewares:
        - name: external-pihole-replacepathregex
      services:
        - name: external-pihole
          kind: Service
          port: 80
  tls:
    secretName: pihole-tls
