apiVersion: v1
kind: Service
metadata:
  name: external-pihole
spec:
  clusterIP: None
  externalIPs:
    - 192.168.0.42
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pihole-cert
spec:
  secretName: pihole-tls
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - pihole.eeternalsadness.dev
---
# Replace the path with /admin
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: external-pihole-addprefix
spec:
  addPrefix:
    prefix: "/admin"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pihole
  annotations:
    gethomepage.dev/href: "https://pihole.eeternalsadness.dev"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Pi-hole
    gethomepage.dev/group: Management
    #gethomepage.dev/icon: emby.png
    gethomepage.dev/name: Pi-hole
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`pihole.eeternalsadness.dev`)
      # middlewares:
      #   - name: external-pihole-addprefix
      services:
        - name: external-pihole
          kind: Service
          port: 80
  tls:
    secretName: pihole-tls
