apiVersion: v1
kind: Service
metadata:
  name: external-postgres
spec:
  type: ExternalName
  externalName: postgres-1.home.lan
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
