apiVersion: v1
kind: Service
metadata:
  name: external-router
spec:
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: router-cert
spec:
  secretName: router-tls
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - router.homelab.eeternalsadness.dev
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: router
  annotations:
    gethomepage.dev/href: "https://router.homelab.eeternalsadness.dev"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Router
    gethomepage.dev/group: Management
    #gethomepage.dev/icon: emby.png
    gethomepage.dev/name: Router
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`router.homelab.eeternalsadness.dev`)
      services:
        - name: external-router
          kind: Service
          port: 80
  tls:
    secretName: router-tls
