apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
spec:
  project: default
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  sources:
    - chart: kube-prometheus-stack
      repoURL: "https://prometheus-community.github.io/helm-charts"
      targetRevision: 70.3.0
      helm:
        valuesFiles:
          - $values/values-grafana.yaml
    - repoURL: "https://github.com/eeternalsadness/homelab.git"
      path: envs/dev/monitoring
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # try to get around annotation size limit
      - ServerSideApply=true
