apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
spec:
  project: default
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  sources:
    - chart: kube-prometheus-stack
      repoURL: "https://prometheus-community.github.io/helm-charts"
      targetRevision: 70.3.0
      helm:
        valueFiles:
          - $values/envs/dev/monitoring/values-grafana.yaml
          - $values/envs/dev/monitoring/values-prometheus.yaml
          - $values/envs/dev/monitoring/values.yaml
    # values files reference
    - repoURL: "https://github.com/eeternalsadness/homelab.git"
      targetRevision: main
      ref: values
    # kustomization for config maps
    #- repoURL: "https://github.com/eeternalsadness/homelab.git"
    #  targetRevision: main
    #  path: envs/dev/monitoring/grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # try to get around annotation size limit
      - ServerSideApply=true
