grafana:
  defaultDashboardsTimezone: Asia/Bangkok
  adminPassword: admin

  # TODO: use this to inject existing secret
  #admin:
  #  # Name of the secret. Can be templated.
  #  existingSecret: ""
  #  userKey: admin-user
  #  passwordKey: admin-password

  #  ingress:
  #    enabled: true
  #    ingressClassName: traefik
  #    path: /grafana

  #resources: {}

  # NOTE: for auto discovery of resources (dashboards, alerts, data sources, etc.)
  #sidecar:
  #  resources: {}
  #  dashboards:
  #    enabled: false
  #    label: grafana_dashboard
  #    labelValue: ""
  #    searchNamespace: ALL # search in all namespaces
  #  alerts:
  #    enabled: false
  #    label: grafana_alert
  #    labelValue: ""
  #    searchNamespace: ALL # search in all namespaces
  #  datasources:
  #    enabled: false
  #    label: grafana_datasource
  #    labelValue: ""
  #    searchNamespace: ALL # search in all namespaces
  #  plugins:
  #    enabled: false
  #    label: grafana_plugin
  #    labelValue: ""
  #    searchNamespace: ALL # search in all namespaces
