grafana:
  defaultDashboardsTimezone: Asia/Bangkok
  # FIXME: store this in vault somehow
  adminPassword: admin

  #  ingress:
  #    enabled: true
  #    ingressClassName: traefik
  #    path: /grafana

  # NOTE: for auto discovery of resources (dashboards, alerts, data sources, etc.)
  sidecar:
    resources: {}
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: ""
      searchNamespace: ALL # search in all namespaces
    alerts:
      enabled: true
      label: grafana_alert
      labelValue: ""
      searchNamespace: ALL # search in all namespaces
    datasources:
      enabled: false
      label: grafana_datasource
      labelValue: ""
      searchNamespace: ALL # search in all namespaces
    plugins:
      enabled: false
      label: grafana_plugin
      labelValue: ""
      searchNamespace: ALL # search in all namespaces
